// Generated by Wrangler by running `wrangler types`

interface Env {
	SOROBAN_RPC_URL: "https://soroban-rpc.lightsail.network";
	STELLAR_NETWORK: "PUBLIC";
	SOROBAN_DOMAINS_VAULTS_CONTRACT_ID: "CATRNPHYKNXAPNLHEYH55REB6YSAJLGCPA4YM6L3WUKSZOPI77M2UMKI";
}
